# Generated by Django 3.2.8 on 2022-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='userid',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
